### ISSUE TITLE
Change repo name to ets-ogcapi-processes20-part2 and package name to org.opengis.cite.ogcapiprocesses20part2

### ISSUE THREAD

**Issue by ghobona** [GeoLabs/ets-ogcapi-processes20#1]
@gfenoy Thanks for this initiative.

We are currently in the process of modifying the executable test suites so that Part 2 standards have separate `ets` repositories from Part 1 standards. 

This is due to constraints on how the validator interfaces with the certification system.

This means that Part 1 v2.0 and Part 2 v2.0 have to have separate repositories.

Could you please change the name of the repo to `ets-ogcapi-processes20-part2` and the name of the packages to `org.opengis.cite.ogcapiprocesses20part2`.

Cc: @bpross-52n @dstenger

**Comment by gfenoy** [comment]
@ghobona, we successfully made the required changes:

* moving the repo to `ets-ogcapi-processes20-part2`
* renaming the package as `org.opengis.cite.ogcapiprocesses20part2`

After the changes, we built and ran the ETS locally successfully.

The documentation and Dockerfiles have been updated consequently.

**Comment by gfenoy** [comment]
> This means that Part 1 v2.0 and Part 2 v2.0 have to have separate repositories.

Could the ETS be hosted in `ets-ogcapi-processes10-part2` repo and the package named `org.opengis.cite.ogcapiprocesses10part2`?

I am asking because there were no OGC API - Processes - Part 2 version 1.0. So, there is no evident reason to version the first version of Part 2 as 2.0.

**Comment by ghobona** [comment]
Yes, `ets-ogcapi-processes10-part2` and `org.opengis.cite.ogcapiprocesses10part2` would be more appropriate.

Thanks for spotting the mistake!

**Comment by gfenoy** [comment]
Sorry for the confusion at the beginning, and thanks for your clarifications.

This issue can now be closed.
