### ISSUE TITLE
When ready for Beta deployment, please move to opengeospatial/ets-ogcapi-processes10-part2

### ISSUE THREAD

**Issue by ghobona** [GeoLabs/ets-ogcapi-processes20#2]
When ready for Beta deployment, please move to https://github.com/opengeospatial/ets-ogcapi-processes10-part2

**Comment by ghobona** [comment]
...or you can move the content sooner.

**Comment by gfenoy** [comment]
It is now available there: https://github.com/opengeospatial/ets-ogcapi-processes10-part2

**Comment by gfenoy** [comment]
Done
